name: Build Release Binaries

on:
  release:
    types:
      - created

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Display the go version and the release tag
        run: |
          go version
          echo "Tag version: ${{ github.event.release.tag_name }}"

      - name: Build binaries
        run: ./.github/scripts/build-executables.sh ${{ github.event.release.tag_name }}

      - name: Upload the binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./release/dobunezumi-*
          file_glob: true
